// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb11SDyjTjALcuOuJUNGptbHkJQnbIkIs',
    appId: '1:455173471672:web:554d0cdd499d8c3e82234d',
    messagingSenderId: '455173471672',
    projectId: 'fitness-tracker-3bae7',
    authDomain: 'fitness-tracker-3bae7.firebaseapp.com',
    storageBucket: 'fitness-tracker-3bae7.firebasestorage.app',
    measurementId: 'G-DNX7KJLFQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVAYkohKqWyiDQR9RxvD-ThZlIjFKXhtw',
    appId: '1:455173471672:android:e9aed3d19df2bf1982234d',
    messagingSenderId: '455173471672',
    projectId: 'fitness-tracker-3bae7',
    storageBucket: 'fitness-tracker-3bae7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb11SDyjTjALcuOuJUNGptbHkJQnbIkIs',
    appId: '1:455173471672:web:9c177b2b255661c682234d',
    messagingSenderId: '455173471672',
    projectId: 'fitness-tracker-3bae7',
    authDomain: 'fitness-tracker-3bae7.firebaseapp.com',
    storageBucket: 'fitness-tracker-3bae7.firebasestorage.app',
    measurementId: 'G-K78ZNTJW5X',
  );
}
